# Generated by Django 4.2.7 on 2024-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolistapp', '0002_remove_todolist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('current_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
